# Generated by Django 3.0.5 on 2020-05-02 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccompaniMent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Therapist', 'Therapist'), ('Psychiatrist', 'Psychiatrist'), ('Doctor', 'Doctor'), ('Family', 'Family'), ('Friend', 'Friend'), ('', 'Any')], default='Friend', max_length=12)),
                ('tel_no', models.CharField(max_length=20)),
                ('tel_no2', models.CharField(max_length=20)),
                ('tel_no3', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='TreatMent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('prescribed_dosage', models.IntegerField()),
                ('doses_per_day', models.IntegerField()),
                ('pills_remaining', models.IntegerField()),
                ('scriptRepeats', models.IntegerField(default=0)),
                ('scriptAvail', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FulfilMent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('category', models.CharField(choices=[('Habit', 'Habit'), ('Hobby', 'Hobby'), ('', 'Any')], default='Habit', max_length=5)),
                ('is_good', models.BooleanField(default=True)),
                ('goal_time', models.IntegerField(blank=True, null=True)),
                ('goal_qty', models.IntegerField(blank=True, null=True)),
                ('total_time', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnjoyMent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ave_mood', models.IntegerField(default=5)),
                ('lowest_mood', models.IntegerField(default=5)),
                ('highest_mood', models.IntegerField(default=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
